version: '3.8'

services:
  radiko-recorder:
    image: ghcr.io/tomacheese/radiko-recorder:v1.0.16
    volumes:
      - type: bind
        source: ./data
        target: /data
    env_file:
      - radiko-recorder.env
